# Generated by Django 2.2.14 on 2020-07-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_postings',
            name='company',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='job_postings',
            name='job_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job_postings',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job_postings',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
