# Generated by Django 2.2.14 on 2020-07-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20200708_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_postings',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job_postings',
            name='job_address',
        ),
    ]
