# Generated by Django 2.2.14 on 2020-07-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20200708_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_postings',
            name='company',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='job_postings',
            name='job_address',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
