# Generated by Django 2.2.14 on 2020-07-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20200708_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_applications',
            name='evaluated_score',
            field=models.IntegerField(default=0),
        ),
    ]
