# Generated by Django 2.2.14 on 2020-07-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_job_applications_evaluated_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applications',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job_applications',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
