# Generated by Django 2.2.14 on 2020-07-12 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_auto_20200712_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applications',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='web_app.Job_postings'),
        ),
    ]
