# Generated by Django 2.2.14 on 2020-07-26 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_auto_20200727_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_applications',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
